import {
  User,
  Subject,
  Category,
  Topic,
  PipelineStageConfig,
  UserTopicProgress,
  StudyMaterial,
  CodingProblem,
  DailyTask,
  DailyJournal,
  MockInterview,
  InterviewQuestion,
  ProjectPortfolio,
  ResumeChecklistItem,
  NotificationScheduleConfig,
  MissionConfig,
  AuditLog,
  VirtualWallet,
  Achievement,
  EconomySettings,
} from "../types";

export const INITIAL_USERS: User[] = [
  {
    id: "user-anuraj",
    email: "anuraj@mission2027.internal",
    fullName: "Anuraj",
    role: "admin",
    avatarUrl: "",
    githubUsername: "anuraj-dev",
    leetcodeUsername: "anuraj_code",
    bio: "Focusing on Core DSA, Low-Level Systems, and SAP HANA In-Memory Computing.",
    targetRole: "SAP Labs Associate Developer",
    createdAt: "2026-10-04T00:00:00.000Z",
    themePreference: "dark",
    timezone: "Asia/Kolkata",
    notificationPreferences: {
      morningReminder: true,
      middayCheck: true,
      eveningReminder: true,
      nightSubmission: true,
      lateReview: true,
      revisionReminders: true,
      mockInterviews: true,
      adminAnnouncements: true,
    },
  },
  {
    id: "user-soumyajit",
    email: "soumyajit@mission2027.internal",
    fullName: "Soumyajit",
    role: "admin",
    avatarUrl: "",
    githubUsername: "soumyajit-dev",
    leetcodeUsername: "soumyajit_algo",
    bio: "Focusing on Database Architecture, ABAP on HANA, Dynamic Programming, and Cloud Computing.",
    targetRole: "SAP Labs Associate Developer",
    createdAt: "2026-10-04T00:00:00.000Z",
    themePreference: "dark",
    timezone: "Asia/Kolkata",
    notificationPreferences: {
      morningReminder: true,
      middayCheck: true,
      eveningReminder: true,
      nightSubmission: true,
      lateReview: true,
      revisionReminders: true,
      mockInterviews: true,
      adminAnnouncements: true,
    },
  },
];

export const INITIAL_MISSION_CONFIG: MissionConfig = {
  title: "SAP LABS — MISSION 2027",
  subtitle: "ANURAJ × SOUMYAJIT",
  startDate: "2026-10-04T00:00:00.000Z",
  targetDeadline: "2027-07-01T00:00:00.000Z",
  isFinalReviewMode: false,
  announcement: {
    active: true,
    text: "Target 1 July 2027: Daily disciplined preparation in DSA, Core Computer Science, and SAP Enterprise Technologies.",
    updatedAt: "2026-10-04T08:00:00.000Z",
  },
  dailyQuotes: [
    "Consistency creates opportunities.",
    "Master the fundamentals, and advanced engineering becomes natural.",
    "Learn it. Revise it. Explain it. Master it.",
    "Two candidates. One target. Zero compromises.",
  ],
  readinessWeights: {
    programming: 15,
    dsa: 25,
    dbms: 15,
    coreCs: 15,
    sap: 15,
    cloud: 10,
    placement: 5,
  },
};

export const INITIAL_PIPELINE_STAGES: PipelineStageConfig[] = [
  {
    id: "stage-1",
    stageNumber: 1,
    name: "Stage 1: Learning / Study",
    shortName: "Study",
    description: "Deep conceptual study, video lectures, documentation, and handwritten notes recording.",
    requirements: [
      "Understand core theoretical principles",
      "Draft structured study notes",
      "Run sample code & dry run algorithms",
    ],
    requiresApproval: false,
    minIntervalDays: 0,
  },
  {
    id: "stage-2",
    stageNumber: 2,
    name: "Stage 2: First Revision",
    shortName: "1st Rev",
    description: "First round of recall reinforcement, standard practice problems, and resolving edge-case doubts.",
    requirements: [
      "Review study notes without external lookups",
      "Solve at least 3 standard practice problems",
      "Record common pitfalls and edge cases",
    ],
    requiresApproval: false,
    minIntervalDays: 3,
  },
  {
    id: "stage-3",
    stageNumber: 3,
    name: "Stage 3: Final Revision",
    shortName: "Final Rev",
    description: "Independent testing under timed conditions without documentation assistance.",
    requirements: [
      "Solve intermediate problem sets independently",
      "Explain concepts aloud or in written summary",
      "Analyze time & space complexity trade-offs",
    ],
    requiresApproval: false,
    minIntervalDays: 7,
  },
  {
    id: "stage-4",
    stageNumber: 4,
    name: "Stage 4: Super Final Revision",
    shortName: "Super Final",
    description: "High-stress problem defense, hard benchmark questions, and weak-area correction.",
    requirements: [
      "Solve hard placement-level benchmark problems",
      "Identify and resolve all tricky conceptual nuances",
      "Complete rapid recall test",
    ],
    requiresApproval: false,
    minIntervalDays: 14,
  },
  {
    id: "stage-5",
    stageNumber: 5,
    name: "Stage 5: Interview Preparation",
    shortName: "Interview Prep",
    description: "Mock interview scenario defense, explaining engineering trade-offs, and technical viva.",
    requirements: [
      "Defend architecture decisions and code line-by-line",
      "Answer technical viva & interview questions crisply",
      "Demonstrate 100% conceptual clarity to peer",
    ],
    requiresApproval: false,
    minIntervalDays: 7,
  },
];

// Exactly the 17 initial subjects specified in Section 4 of prompt
export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: "sub-c",
    name: "C Programming",
    code: "C",
    icon: "Code2",
    description: "Pointers, dynamic memory management, bitwise operations, memory layout, and runtime stack.",
    orderIndex: 1,
  },
  {
    id: "sub-cpp",
    name: "C++",
    code: "CPP",
    icon: "Code2",
    description: "Object-oriented programming, virtual functions, STL containers, smart pointers, and RAII.",
    orderIndex: 2,
  },
  {
    id: "sub-python",
    name: "Python",
    code: "PYTHON",
    icon: "Terminal",
    description: "Python memory model, GIL, decorators, generators, dunder methods, and object-oriented paradigms.",
    orderIndex: 3,
  },
  {
    id: "sub-dsa",
    name: "DSA",
    code: "DSA",
    icon: "Binary",
    description: "Data Structures & Algorithms: Arrays, Strings, Trees, Graphs, Dynamic Programming, and Complexity.",
    orderIndex: 4,
  },
  {
    id: "sub-dbms",
    name: "DBMS",
    code: "DBMS",
    icon: "Database",
    description: "ACID properties, relational modeling, normalization, transaction isolation levels, and indexing.",
    orderIndex: 5,
  },
  {
    id: "sub-sql",
    name: "SQL",
    code: "SQL",
    icon: "Table",
    description: "Advanced SQL queries, complex joins, window functions, CTEs, and query optimization.",
    orderIndex: 6,
  },
  {
    id: "sub-os",
    name: "Operating Systems",
    code: "OS",
    icon: "Cpu",
    description: "Process management, CPU scheduling, synchronization, deadlocks, and virtual memory.",
    orderIndex: 7,
  },
  {
    id: "sub-cn",
    name: "Computer Networks",
    code: "CN",
    icon: "Network",
    description: "OSI & TCP/IP models, TCP 3-way handshake, HTTP/HTTPS, DNS, and socket communication.",
    orderIndex: 8,
  },
  {
    id: "sub-oop",
    name: "OOP",
    code: "OOP",
    icon: "Boxes",
    description: "Encapsulation, abstraction, inheritance, polymorphism, SOLID principles, and design patterns.",
    orderIndex: 9,
  },
  {
    id: "sub-sap-fund",
    name: "SAP Fundamentals",
    code: "SAP-FUND",
    icon: "Layers",
    description: "ERP architecture, 3-tier client/server architecture, SAP NetWeaver, and business suites.",
    orderIndex: 10,
  },
  {
    id: "sub-sap-hana",
    name: "SAP HANA",
    code: "SAP-HANA",
    icon: "Server",
    description: "In-memory database engine, columnar storage, calculation views, and code-to-data paradigm.",
    orderIndex: 11,
  },
  {
    id: "sub-abap",
    name: "ABAP",
    code: "ABAP",
    icon: "FileCode",
    description: "ABAP syntax, internal tables, Open SQL, CDS views, AMDP, and ABAP on HANA.",
    orderIndex: 12,
  },
  {
    id: "sub-cloud",
    name: "Cloud Computing",
    code: "CLOUD",
    icon: "Cloud",
    description: "IaaS, PaaS, SaaS, Docker containerization, Kubernetes basics, and cloud deployment models.",
    orderIndex: 13,
  },
  {
    id: "sub-linux",
    name: "Linux",
    code: "LINUX",
    icon: "Terminal",
    description: "Linux file system hierarchy, permissions, bash scripting, process control, and core utilities.",
    orderIndex: 14,
  },
  {
    id: "sub-aptitude",
    name: "Aptitude",
    code: "APTITUDE",
    icon: "Calculator",
    description: "Quantitative ability, logical reasoning, data interpretation, and problem speed mastery.",
    orderIndex: 15,
  },
  {
    id: "sub-communication",
    name: "Communication",
    code: "COMM",
    icon: "MessageSquare",
    description: "STAR method interview responses, active listening, clear articulation, and corporate speaking.",
    orderIndex: 16,
  },
  {
    id: "sub-tech-interview",
    name: "Technical Interview Preparation",
    code: "TECH-INT",
    icon: "Briefcase",
    description: "System design basics, live whiteboard coding, project architecture defense, and core interview Q&A.",
    orderIndex: 17,
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-c-core", subjectId: "sub-c", name: "Core C", description: "Pointers and memory allocation", orderIndex: 1 },
  { id: "cat-cpp-core", subjectId: "sub-cpp", name: "Modern C++", description: "OOP, STL, and memory safety", orderIndex: 1 },
  { id: "cat-python-core", subjectId: "sub-python", name: "Python Systems", description: "Internals and language paradigms", orderIndex: 1 },
  { id: "cat-dsa-arrays", subjectId: "sub-dsa", name: "Arrays & Strings", description: "Sliding window and two pointers", orderIndex: 1 },
  { id: "cat-dsa-trees", subjectId: "sub-dsa", name: "Trees & Graphs", description: "Binary trees, BST, BFS/DFS, Dijkstra", orderIndex: 2 },
  { id: "cat-dsa-dp", subjectId: "sub-dsa", name: "Dynamic Programming", description: "Knapsack, LCS, LIS, Matrix DP", orderIndex: 3 },
  { id: "cat-dbms-core", subjectId: "sub-dbms", name: "Database Systems", description: "ACID, normalization, indexing", orderIndex: 1 },
  { id: "cat-sql-core", subjectId: "sub-sql", name: "SQL Mastery", description: "Complex joins and window queries", orderIndex: 1 },
  { id: "cat-os-core", subjectId: "sub-os", name: "OS Internals", description: "Processes, synchronization, memory", orderIndex: 1 },
  { id: "cat-cn-core", subjectId: "sub-cn", name: "Networking Stack", description: "TCP/IP, HTTP, DNS", orderIndex: 1 },
  { id: "cat-oop-core", subjectId: "sub-oop", name: "OOP & SOLID", description: "Pillars and design patterns", orderIndex: 1 },
  { id: "cat-sap-fund-core", subjectId: "sub-sap-fund", name: "Enterprise Architecture", description: "3-tier architecture & ERP", orderIndex: 1 },
  { id: "cat-sap-hana-core", subjectId: "sub-sap-hana", name: "HANA Engine", description: "Columnar store & in-memory", orderIndex: 1 },
  { id: "cat-abap-core", subjectId: "sub-abap", name: "ABAP & CDS", description: "ABAP syntax, internal tables, CDS views", orderIndex: 1 },
  { id: "cat-cloud-core", subjectId: "sub-cloud", name: "Containers & Cloud", description: "Docker, microservices, cloud models", orderIndex: 1 },
  { id: "cat-linux-core", subjectId: "sub-linux", name: "Linux Administration", description: "Shell scripting, permissions, processes", orderIndex: 1 },
  { id: "cat-aptitude-core", subjectId: "sub-aptitude", name: "Placement Aptitude", description: "Quantitative & logical ability", orderIndex: 1 },
  { id: "cat-comm-core", subjectId: "sub-communication", name: "Professional Speech", description: "STAR method & articulation", orderIndex: 1 },
  { id: "cat-tech-int-core", subjectId: "sub-tech-interview", name: "Technical Viva", description: "System design & whiteboard coding", orderIndex: 1 },
];

export const INITIAL_TOPICS: Topic[] = [
  // C Programming
  {
    id: "top-c-pointers",
    categoryId: "cat-c-core",
    subjectId: "sub-c",
    name: "Pointers & Dynamic Memory Management",
    description: "Pointer arithmetic, void pointers, malloc/calloc/realloc/free, memory leaks, and segmentation faults.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 12,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Pointer arithmetic", "Function pointers", "Dynamic memory allocation", "Memory alignment & padding"],
  },
  {
    id: "top-c-structs",
    categoryId: "cat-c-core",
    subjectId: "sub-c",
    name: "Structures, Unions & Bitwise Operations",
    description: "Memory layout of structs, union overlapping, bitfields, masking, and endianness handling.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 8,
    assignedTo: "all",
    orderIndex: 2,
    isActive: true,
    subtopics: ["Struct padding & packing", "Unions memory usage", "Bitwise masking", "Endianness"],
  },

  // C++
  {
    id: "top-cpp-stl",
    categoryId: "cat-cpp-core",
    subjectId: "sub-cpp",
    name: "C++ STL & Modern Memory Model",
    description: "std::vector internals, red-black tree in std::map, smart pointers (unique/shared/weak), and RAII.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 14,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Vector growth factor", "Map vs Unordered Map", "Smart pointers & reference counting", "Move semantics & rvalues"],
  },
  {
    id: "top-cpp-vtable",
    categoryId: "cat-cpp-core",
    subjectId: "sub-cpp",
    name: "Virtual Functions & VTable Mechanism",
    description: "Runtime polymorphism, vptr and vtable layout, pure virtual functions, and abstract base classes.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 2,
    isActive: true,
    subtopics: ["VTable & VPTR mechanics", "Object slicing", "Multiple inheritance ambiguities", "Virtual destructors"],
  },

  // Python
  {
    id: "top-py-internals",
    categoryId: "cat-python-core",
    subjectId: "sub-python",
    name: "Python Internals, GIL & Memory Management",
    description: "Reference counting, garbage collection cycles, GIL implications, and generators vs iterators.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["GIL & concurrency", "Reference counting GC", "Decorators & closures", "Generators & yield"],
  },

  // DSA
  {
    id: "top-dsa-arrays-sliding",
    categoryId: "cat-dsa-arrays",
    subjectId: "sub-dsa",
    name: "Sliding Window & Two Pointer Technique",
    description: "Variable and fixed-size sliding window, Kadane's algorithm, Dutch National Flag, and prefix sums.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 18,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Fixed-size window", "Dynamic window with HashMap", "Two pointers opposite ends", "Prefix sum difference arrays"],
  },
  {
    id: "top-dsa-trees-graphs",
    categoryId: "cat-dsa-trees",
    subjectId: "sub-dsa",
    name: "Binary Trees, BST & Graph Traversals",
    description: "Tree traversals, lowest common ancestor, diameter, BFS, DFS, Dijkstra, and Topological Sort.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 24,
    assignedTo: "all",
    orderIndex: 2,
    isActive: true,
    subtopics: ["Tree traversals & LCA", "BST validation", "BFS & DFS graph patterns", "Dijkstra shortest path algorithm"],
  },
  {
    id: "top-dsa-dp-core",
    categoryId: "cat-dsa-dp",
    subjectId: "sub-dsa",
    name: "Dynamic Programming Foundations & Patterns",
    description: "0/1 Knapsack, Longest Common Subsequence (LCS), Longest Increasing Subsequence (LIS), and Matrix DP.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 26,
    assignedTo: "all",
    orderIndex: 3,
    isActive: true,
    subtopics: ["0/1 Knapsack pattern", "LCS & String DP", "LIS O(N log N) patience sorting", "Grid DP paths"],
  },

  // DBMS
  {
    id: "top-dbms-acid",
    categoryId: "cat-dbms-core",
    subjectId: "sub-dbms",
    name: "ACID Transactions & Concurrency Control",
    description: "Atomicity, Consistency, Isolation levels, Durability, Two-Phase Locking (2PL), and deadlock prevention.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 12,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Transaction isolation levels", "Dirty read, non-repeatable, phantom read", "2PL protocol", "Deadlock detection"],
  },
  {
    id: "top-dbms-norm",
    categoryId: "cat-dbms-core",
    subjectId: "sub-dbms",
    name: "Normalization & Indexing Internals",
    description: "1NF to BCNF rules, functional dependencies, B-Tree and B+ Tree indexing structures, and clustered indexes.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 2,
    isActive: true,
    subtopics: ["1NF, 2NF, 3NF, BCNF", "B+ Tree vs Hash indexing", "Clustered vs Non-clustered index", "Query execution plan"],
  },

  // SQL
  {
    id: "top-sql-joins-window",
    categoryId: "cat-sql-core",
    subjectId: "sub-sql",
    name: "Complex SQL Joins & Window Functions",
    description: "INNER/OUTER/CROSS joins, ROW_NUMBER(), RANK(), DENSE_RANK(), LEAD(), LAG(), and CTE aggregations.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 12,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Window functions (RANK, DENSE_RANK)", "CTEs and recursive queries", "Self joins & outer joins", "Aggregation with HAVING"],
  },

  // Operating Systems
  {
    id: "top-os-process-threads",
    categoryId: "cat-os-core",
    subjectId: "sub-os",
    name: "Processes, Threads & Synchronization",
    description: "Process lifecycle, PCB, context switching, mutex, semaphores, producer-consumer, and critical section.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 16,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Process vs Thread memory layout", "Mutex vs Semaphore", "Deadlocks & Banker's algorithm", "CPU scheduling algorithms"],
  },
  {
    id: "top-os-virtual-memory",
    categoryId: "cat-os-core",
    subjectId: "sub-os",
    name: "Virtual Memory, Paging & Page Replacement",
    description: "Paging, page tables, TLB, page faults, thrashing, and LRU page replacement algorithm.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 12,
    assignedTo: "all",
    orderIndex: 2,
    isActive: true,
    subtopics: ["Paging & TLB lookup", "Page fault handling", "Thrashing causes and resolution", "LRU and FIFO algorithms"],
  },

  // Computer Networks
  {
    id: "top-cn-tcp-handshake",
    categoryId: "cat-cn-core",
    subjectId: "sub-cn",
    name: "TCP/IP Protocol Suite & Handshakes",
    description: "TCP 3-way handshake, connection teardown, TCP flow control, sliding window, and UDP comparisons.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 12,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["TCP 3-Way Handshake SYN/ACK", "TCP vs UDP tradeoffs", "Flow & congestion control", "DNS resolution flow"],
  },

  // OOP
  {
    id: "top-oop-solid",
    categoryId: "cat-oop-core",
    subjectId: "sub-oop",
    name: "SOLID Principles & Core Design Patterns",
    description: "Four OOP pillars, Single Responsibility, Open-Closed, Liskov, Factory, Singleton, and Observer patterns.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 14,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Four pillars in depth", "SOLID principles with real examples", "Factory & Singleton pattern", "Observer & Strategy pattern"],
  },

  // SAP Fundamentals
  {
    id: "top-sap-3tier",
    categoryId: "cat-sap-fund-core",
    subjectId: "sub-sap-fund",
    name: "SAP 3-Tier Client/Server Architecture & ERP",
    description: "Presentation, application, database layer, SAP NetWeaver, dispatcher, and ERP module interactions.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["3-Tier architecture flow", "SAP Work Process types", "ERP core business flows", "SAP GUI vs SAP Fiori"],
  },

  // SAP HANA
  {
    id: "top-sap-hana-columnar",
    categoryId: "cat-sap-hana-core",
    subjectId: "sub-sap-hana",
    name: "SAP HANA In-Memory Engine & Columnar Storage",
    description: "In-memory database architecture, row vs column store, delta merge mechanism, and calculation views.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 16,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Columnar compression algorithms", "Delta store and Main store merge", "Code-to-data paradigm", "Calculation Views"],
  },

  // ABAP
  {
    id: "top-abap-syntax-cds",
    categoryId: "cat-abap-core",
    subjectId: "sub-abap",
    name: "ABAP Syntax, Internal Tables & Core Data Services (CDS)",
    description: "ABAP standard data types, standard/sorted/hashed internal tables, Open SQL, and CDS views on HANA.",
    priority: "CRITICAL",
    difficulty: "MEDIUM",
    estimatedHours: 14,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Internal table types & performance", "Work areas & field symbols", "ABAP Open SQL queries", "Core Data Services (CDS) Views"],
  },

  // Cloud Computing
  {
    id: "top-cloud-docker",
    categoryId: "cat-cloud-core",
    subjectId: "sub-cloud",
    name: "Cloud Models, Microservices & Docker",
    description: "IaaS/PaaS/SaaS, Docker containerization, Dockerfiles, multi-stage builds, and microservices architecture.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["IaaS vs PaaS vs SaaS", "Docker vs Virtual Machines", "Dockerfile optimization", "Container networking basics"],
  },

  // Linux
  {
    id: "top-linux-admin",
    categoryId: "cat-linux-core",
    subjectId: "sub-linux",
    name: "Linux File System & Bash Scripting",
    description: "File permissions (chmod, chown), process management (ps, top, kill), pipelines, and bash automation.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 10,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Permission bit calculation", "Bash scripting & loops", "Pipes, grep, awk, sed", "Process signals & systemd"],
  },

  // Aptitude
  {
    id: "top-aptitude-quant",
    categoryId: "cat-aptitude-core",
    subjectId: "sub-aptitude",
    name: "Quantitative & Analytical Aptitude",
    description: "Time & work, speed & distance, percentages, permutations & combinations, and logical deduction.",
    priority: "HIGH",
    difficulty: "MEDIUM",
    estimatedHours: 14,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Time, speed and distance shortcuts", "Work and wages formulas", "Probability & combinations", "Data interpretation charts"],
  },

  // Communication
  {
    id: "top-comm-star",
    categoryId: "cat-comm-core",
    subjectId: "sub-communication",
    name: "Professional Articulation & STAR Method",
    description: "Structuring placement answers using Situation, Task, Action, Result, active listening, and concise speaking.",
    priority: "HIGH",
    difficulty: "EASY",
    estimatedHours: 8,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["STAR interview framework", "Self-introduction formula", "Handling behavioral dilemmas", "Professional technical pitch"],
  },

  // Technical Interview Preparation
  {
    id: "top-tech-int-system-design",
    categoryId: "cat-tech-int-core",
    subjectId: "sub-tech-interview",
    name: "System Design Basics & Whiteboard Coding",
    description: "Load balancers, caching strategies, horizontal scaling, database sharding, and live coding viva.",
    priority: "CRITICAL",
    difficulty: "HARD",
    estimatedHours: 18,
    assignedTo: "all",
    orderIndex: 1,
    isActive: true,
    subtopics: ["Scaling & load balancing", "Caching (Redis/Memcached)", "Database sharding vs replication", "Whiteboard problem explanation"],
  },
];

// Initial individual progress records for Anuraj & Soumyajit
export const INITIAL_USER_PROGRESS: UserTopicProgress[] = [
  // Anuraj's Progress
  {
    id: "prog-anuraj-c",
    userId: "user-anuraj",
    topicId: "top-c-pointers",
    currentStage: 3, // Final Revision
    isMastered: false,
    confidenceLevel: 4,
    notes: "Pointers and memory leaks clear. Need to revise void pointers & function callbacks.",
    lastStudiedAt: "2026-10-04T09:30:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-10-01T12:00:00.000Z", score: 5 },
      { stageNumber: 2, stageName: "Stage 2: First Revision", completedAt: "2026-10-03T15:00:00.000Z", score: 4 },
    ],
  },
  {
    id: "prog-anuraj-dsa-arrays",
    userId: "user-anuraj",
    topicId: "top-dsa-arrays-sliding",
    currentStage: 4, // Super Final Revision
    isMastered: false,
    confidenceLevel: 5,
    notes: "Sliding window problems mastered. Solved 15 LeetCode problems.",
    lastStudiedAt: "2026-10-04T11:00:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-09-28T10:00:00.000Z", score: 5 },
      { stageNumber: 2, stageName: "Stage 2: First Revision", completedAt: "2026-10-01T14:00:00.000Z", score: 5 },
      { stageNumber: 3, stageName: "Stage 3: Final Revision", completedAt: "2026-10-03T18:00:00.000Z", score: 4 },
    ],
  },
  {
    id: "prog-anuraj-hana",
    userId: "user-anuraj",
    topicId: "top-sap-hana-columnar",
    currentStage: 2, // First Revision
    isMastered: false,
    confidenceLevel: 4,
    notes: "Studied columnar compression and delta store merge mechanism.",
    lastStudiedAt: "2026-10-04T08:00:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-10-02T16:00:00.000Z", score: 4 },
    ],
  },

  // Soumyajit's Progress
  {
    id: "prog-soumya-dbms",
    userId: "user-soumyajit",
    topicId: "top-dbms-acid",
    currentStage: 4, // Super Final Revision
    isMastered: false,
    confidenceLevel: 5,
    notes: "ACID properties and isolation anomalies (phantom read, non-repeatable) thoroughly clear.",
    lastStudiedAt: "2026-10-04T10:00:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-09-29T11:00:00.000Z", score: 5 },
      { stageNumber: 2, stageName: "Stage 2: First Revision", completedAt: "2026-10-02T14:00:00.000Z", score: 5 },
      { stageNumber: 3, stageName: "Stage 3: Final Revision", completedAt: "2026-10-03T19:00:00.000Z", score: 5 },
    ],
  },
  {
    id: "prog-soumya-sql",
    userId: "user-soumyajit",
    topicId: "top-sql-joins-window",
    currentStage: 3, // Final Revision
    isMastered: false,
    confidenceLevel: 4,
    notes: "Practicing DENSE_RANK, LEAD, LAG queries on real datasets.",
    lastStudiedAt: "2026-10-04T11:30:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-09-30T10:00:00.000Z", score: 5 },
      { stageNumber: 2, stageName: "Stage 2: First Revision", completedAt: "2026-10-02T16:00:00.000Z", score: 4 },
    ],
  },
  {
    id: "prog-soumya-dsa-dp",
    userId: "user-soumyajit",
    topicId: "top-dsa-dp-core",
    currentStage: 2, // First Revision
    isMastered: false,
    confidenceLevel: 3,
    notes: "0/1 Knapsack recurrence understood. Solving LCS variations.",
    lastStudiedAt: "2026-10-04T09:00:00.000Z",
    stageHistory: [
      { stageNumber: 1, stageName: "Stage 1: Learning / Study", completedAt: "2026-10-02T15:00:00.000Z", score: 4 },
    ],
  },
];

// Initial Study Materials
export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: "mat-1",
    topicId: "top-c-pointers",
    subjectId: "sub-c",
    title: "C Pointers & Memory Layout Architecture Guide",
    type: "pdf",
    contentUrl: "https://www.cs.yale.edu/homes/aspnes/pinewiki/C(2f)Pointers.html",
    description: "Deep dive into pointer arithmetic, function pointers, and stack frame memory diagrams.",
    isPrivate: false,
    uploadedBy: "Anuraj",
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mat-2",
    topicId: "top-sap-hana-columnar",
    subjectId: "sub-sap-hana",
    title: "SAP HANA In-Memory Columnar Database Deep Dive",
    type: "video_url",
    contentUrl: "https://www.youtube.com/watch?v=0h5k8m8rR0k",
    description: "Technical lecture on columnar storage, dictionary compression, and delta merge engine.",
    isPrivate: false,
    uploadedBy: "Soumyajit",
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mat-3",
    topicId: "top-dbms-acid",
    subjectId: "sub-dbms",
    title: "Database Transaction Isolation Levels & 2PL Notes",
    type: "note",
    contentUrl: "Detailed breakdown of Read Uncommitted, Read Committed, Repeatable Read, and Serializable.",
    description: "Comprehensive notes with concurrency anomalies matrix.",
    isPrivate: false,
    uploadedBy: "Soumyajit",
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mat-4",
    topicId: "top-dsa-trees-graphs",
    subjectId: "sub-dsa",
    title: "Graph Traversal & Dijkstra Implementation Guide",
    type: "doc_url",
    contentUrl: "https://cp-algorithms.com/graph/dijkstra.html",
    description: "CP-Algorithms reference for standard Dijkstra with priority queue.",
    isPrivate: false,
    uploadedBy: "Anuraj",
    createdAt: "2026-10-04T00:00:00.000Z",
  },
];

// Initial LeetCode Problems Logged (Starts clean with 0 records for genuine tracking)
export const INITIAL_CODING_PROBLEMS: CodingProblem[] = [];

// Initial Daily Tasks: Today, Pending, Completed, Overdue
export const INITIAL_DAILY_TASKS: DailyTask[] = [
  // Anuraj's Tasks
  {
    id: "task-a-1",
    userId: "user-anuraj",
    title: "Solve 2 Medium Problems on Sliding Window",
    description: "LeetCode #209 and #424 focus.",
    priority: "CRITICAL",
    category: "DSA Practice",
    targetDate: "2026-10-04", // Today
    status: "TODO",
    isSharedTask: false,
    estimatedMinutes: 60,
  },
  {
    id: "task-a-2",
    userId: "user-anuraj",
    title: "Revise C Pointers & Function Callbacks",
    description: "Read documentation on function pointer syntax and void* casting.",
    priority: "HIGH",
    category: "C Programming",
    targetDate: "2026-10-04", // Today
    status: "TODO",
    isSharedTask: false,
    estimatedMinutes: 45,
  },
  {
    id: "task-a-3",
    userId: "user-anuraj",
    title: "SAP HANA In-Memory Columnar Architecture Notes",
    description: "Summarize Delta Store vs Main Store merge algorithms.",
    priority: "HIGH",
    category: "SAP HANA",
    targetDate: "2026-10-05", // Pending
    status: "TODO",
    isSharedTask: true,
    estimatedMinutes: 60,
  },
  {
    id: "task-a-4",
    userId: "user-anuraj",
    title: "Solved Two Sum & 3Sum Implementation",
    description: "C++ implementation with two pointers.",
    priority: "HIGH",
    category: "DSA Practice",
    targetDate: "2026-10-04",
    status: "COMPLETED",
    isSharedTask: false,
    estimatedMinutes: 45,
    completedAt: "2026-10-04T12:00:00.000Z",
  },
  {
    id: "task-a-5",
    userId: "user-anuraj",
    title: "Setup Operating Systems Process Scheduling Notes",
    description: "Compare Round Robin and Multilevel Feedback Queue.",
    priority: "MEDIUM",
    category: "Operating Systems",
    targetDate: "2026-10-02", // Overdue
    status: "OVERDUE",
    isSharedTask: false,
    estimatedMinutes: 40,
  },

  // Soumyajit's Tasks
  {
    id: "task-s-1",
    userId: "user-soumyajit",
    title: "Practice 5 SQL Window Function Queries",
    description: "Focus on ROW_NUMBER(), DENSE_RANK(), and LAG() queries.",
    priority: "CRITICAL",
    category: "SQL",
    targetDate: "2026-10-04", // Today
    status: "TODO",
    isSharedTask: false,
    estimatedMinutes: 60,
  },
  {
    id: "task-s-2",
    userId: "user-soumyajit",
    title: "Revise ACID Properties & 2PL Protocol",
    description: "Understand strict 2PL vs rigorous 2PL and phantom reads.",
    priority: "HIGH",
    category: "DBMS",
    targetDate: "2026-10-04", // Today
    status: "TODO",
    isSharedTask: false,
    estimatedMinutes: 45,
  },
  {
    id: "task-s-3",
    userId: "user-soumyajit",
    title: "SAP HANA In-Memory Columnar Architecture Notes",
    description: "Summarize Delta Store vs Main Store merge algorithms.",
    priority: "HIGH",
    category: "SAP HANA",
    targetDate: "2026-10-05", // Pending
    status: "TODO",
    isSharedTask: true,
    estimatedMinutes: 60,
  },
  {
    id: "task-s-4",
    userId: "user-soumyajit",
    title: "Completed Container With Most Water",
    description: "Python solution with O(1) space.",
    priority: "HIGH",
    category: "DSA Practice",
    targetDate: "2026-10-04",
    status: "COMPLETED",
    isSharedTask: false,
    estimatedMinutes: 30,
    completedAt: "2026-10-04T11:45:00.000Z",
  },
  {
    id: "task-s-5",
    userId: "user-soumyajit",
    title: "Review B-Tree and B+ Tree Index Differences",
    description: "Clarify fanout and leaf node sequential links.",
    priority: "HIGH",
    category: "DBMS",
    targetDate: "2026-10-03", // Overdue
    status: "OVERDUE",
    isSharedTask: false,
    estimatedMinutes: 40,
  },
];

// Initial Notification Schedules: 8 AM, 1 PM, 9 PM
export const INITIAL_NOTIFICATION_SCHEDULES: NotificationScheduleConfig[] = [
  {
    id: "sched-1",
    time: "08:00",
    title: "Morning Mission Kick-Off",
    defaultMessage: "Start today's preparation. Check your today tasks and LeetCode target.",
    category: "morning",
    enabled: true,
  },
  {
    id: "sched-2",
    time: "13:00",
    title: "Midday Checkpoint",
    defaultMessage: "Check your midday progress. Have you solved today's DSA problem?",
    category: "midday",
    enabled: true,
  },
  {
    id: "sched-3",
    time: "21:00",
    title: "Daily Progress Update",
    defaultMessage: "Complete your daily progress update. Log solves and review remaining topics.",
    category: "night",
    enabled: true,
  },
];

export const INITIAL_DAILY_JOURNALS: DailyJournal[] = [];
export const INITIAL_MOCK_INTERVIEWS: MockInterview[] = [];
export const INITIAL_INTERVIEW_QUESTIONS: InterviewQuestion[] = [];
export const INITIAL_PROJECT_PORTFOLIOS: ProjectPortfolio[] = [];
export const INITIAL_RESUME_CHECKLIST: ResumeChecklistItem[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-seed-1",
    timestamp: "2026-10-04T00:00:00.000Z",
    userId: "user-anuraj",
    userName: "Anuraj",
    action: "INITIALIZE_MISSION",
    entityType: "System",
    details: "SAP Labs Mission 2027 workspace initialized. Anuraj × Soumyajit.",
  },
];

// Initial Game Economy & Virtual Money Settings
export const INITIAL_ECONOMY_SETTINGS: EconomySettings = {
  coinsPerProblem: 100, // ₹100 per solve
  coinsPerStreakDay: 250, // ₹250 for maintaining daily streak
  coinsPerTopicMastered: 500, // ₹500 for completing a topic through all 5 stages
  coinsPerTaskCompleted: 50, // ₹50 per task completed
  currencySymbol: "₹",
  currencyName: "Prep Cash",
};

// Initial Wallets for Anuraj and Soumyajit (Independent balances)
export const INITIAL_VIRTUAL_WALLETS: VirtualWallet[] = [
  {
    userId: "user-anuraj",
    balance: 0,
    totalEarned: 0,
    transactions: [],
  },
  {
    userId: "user-soumyajit",
    balance: 0,
    totalEarned: 0,
    transactions: [],
  },
];

// Initial Game Achievements & Awards (Clean, motivating, placement-focused)
export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-first-blood",
    title: "First Solve (Day 1 Recruit)",
    description: "Solve your very first DSA problem in the mission.",
    icon: "Zap",
    category: "SOLVES",
    rewardAmount: 200,
    targetCount: 1,
    unlockedUsers: [],
  },
  {
    id: "ach-10-in-5",
    title: "5-Day Sprint (10 Problems in 5 Days)",
    description: "Solve 10 problems within a 5-day preparation span.",
    icon: "Flame",
    category: "SPECIAL",
    rewardAmount: 1000,
    targetCount: 10,
    unlockedUsers: [],
  },
  {
    id: "ach-7-streak",
    title: "Consistency Warrior (7-Day Streak)",
    description: "Solve problems consistently for 7 unbroken consecutive days.",
    icon: "Award",
    category: "STREAK",
    rewardAmount: 1500,
    targetCount: 7,
    unlockedUsers: [],
  },
  {
    id: "ach-20-streak",
    title: "Unstoppable Discipline (20-Day Continuous Streak)",
    description: "Maintain an unbroken 20-day daily problem-solving streak.",
    icon: "Trophy",
    category: "STREAK",
    rewardAmount: 5000,
    targetCount: 20,
    unlockedUsers: [],
  },
  {
    id: "ach-50-problems",
    title: "Half-Century Hacker (50 Problems Solved)",
    description: "Solve 50 coding problems across DSA and Core CS.",
    icon: "Coins",
    category: "SOLVES",
    rewardAmount: 3500,
    targetCount: 50,
    unlockedUsers: [],
  },
  {
    id: "ach-100-problems",
    title: "Century Grandmaster (100 Problems Solved)",
    description: "Solve 100 coding problems with independent candidate records.",
    icon: "Crown",
    category: "SOLVES",
    rewardAmount: 10000,
    targetCount: 100,
    unlockedUsers: [],
  },
  {
    id: "ach-5-topics",
    title: "Stage 5 Architect (5 Topics Mastered)",
    description: "Complete 5 topics across all 5 revision and interview prep stages.",
    icon: "CheckCircle",
    category: "TOPICS",
    rewardAmount: 3000,
    targetCount: 5,
    unlockedUsers: [],
  },
  {
    id: "ach-sap-elite",
    title: "SAP Labs Placement Elite",
    description: "Achieve a 30-day streak with 75+ problems solved.",
    icon: "Crown",
    category: "SPECIAL",
    rewardAmount: 15000,
    targetCount: 75,
    unlockedUsers: [],
  },
];

// Initial Dynamic LeetCode Topics
export const INITIAL_LEETCODE_TOPICS: string[] = [
  "Arrays",
  "Strings",
  "Two Pointers",
  "Sliding Window",
  "Hashing & Maps",
  "Linked Lists",
  "Stacks & Queues",
  "Trees & Binary Search Trees",
  "Heaps & Priority Queues",
  "Recursion & Backtracking",
  "Dynamic Programming",
  "Greedy Algorithms",
  "Graphs (BFS / DFS)",
  "Bit Manipulation",
  "Trie",
  "SQL Queries",
  "SAP / ABAP Business Logic",
];
